# Generated by Django 4.0.5 on 2022-09-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_userform_register_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userform',
        ),
    ]
