# Generated by Django 4.0.5 on 2022-09-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_userform'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=50)),
                ('phone', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('headrid', models.TextField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
