# Generated by Django 4.0.5 on 2022-09-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_register_employess_register_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerid', models.TextField()),
                ('userid', models.TextField()),
                ('date', models.DateField()),
                ('employe', models.TextField()),
            ],
        ),
    ]
